sylius_grid:
    templates:
        action:
            pick_winner: "@SetonoSyliusGoogleOptimizePlugin/admin/grid/action/pick_winner.html.twig"
    grids:
        setono_sylius_google_optimize_admin_experiment:
            driver:
                options:
                    class: "%setono_sylius_google_optimize.model.experiment.class%"
            limits: [100, 250, 500, 1000]
            fields:
                code:
                    type: string
                    label: setono_sylius_google_optimize.ui.code
                googleExperimentId:
                    type: string
                    label: setono_sylius_google_optimize.ui.google_experiment_id
                variants:
                    type: twig
                    label: setono_sylius_google_optimize.ui.variants
                    path: .
                    options:
                        template: "@SetonoSyliusGoogleOptimizePlugin/admin/grid/field/variants.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [ googleExperimentId, code ]
            actions:
                main:
                    create:
                        type: create
                item:
                    delete:
                        type: delete
                    pick_winner:
                        type: pick_winner
                        label: setono_sylius_google_optimize.ui.pick_winner
                        options:
                            experiment: resource.id
                            variants: resource.variants
                            hidden: resource.hasWinner

